vim.api.nvim_command('source $HOME/.config/nvim/general/settings.vim')
vim.api.nvim_command('source $HOME/.config/nvim/keys/mappings.vim')
vim.api.nvim_command('source $HOME/.config/nvim/vim-plug/plugins.vim')
vim.api.nvim_command('source $HOME/.config/nvim/modules/coc.vim')
vim.api.nvim_command('source $HOME/.config/nvim/modules/startify.vim')
vim.api.nvim_command('source $HOME/.config/nvim/themes/onedark.vim')
